CC          = gcc
CLINKER     = gcc

CFLAGS      = -Wall -O2 -g 
LIBS        = -lm
DEPEND= makedepend

SRC     = ran_uniform.c umbrella.c
OBJS    = ran_uniform.o umbrella.o
EXECS   = umbrella.exe

default: umbrella

all: umbrella

umbrella:$(OBJS)
	$(CLINKER) $(OPTFLAGS) -o $(EXECS) $(OBJS) $(LIBS)

clean:
	/bin/rm -f *.o *~ $(EXECS)

.c.o:
	$(CC) $(CFLAGS) -c $*.c
