PLUMED_RUNTIME_LOAD= "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/plumed/obj/Plumed.o" -ldl  
PLUMED_STATIC_LOAD= "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/plumed/obj/kernel.o" "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/plumed/obj/PlumedStatic.o" -ldl  -lz -ldl   -rdynamic -fopenmp 
PLUMED_SHARED_LOAD= "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/libplumed.so" -ldl  
PLUMED_RUNTIME_DEPENDENCIES=
PLUMED_STATIC_DEPENDENCIES= "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/plumed/obj/kernel.o" "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/plumed/obj/PlumedStatic.o"
PLUMED_SHARED_DEPENDENCIES= "/home/kewei/molsim2024/Exercises2024/Chapter08-PMD/plumed/plumed-2.3.0/lib/libplumed.so"
