#! /bin/csh -f
#
# Scriptfile
#
# rho    = density
# lmax   = number of steps
# nequil = number of equilibration steps
# dr     = maximum displacement
# npart  = number of particles

foreach rho (0.90)

cat > input  <<endofdata
  ibeg  nequil   lmax  nsamp  
     0   5000    10000      1        
    dr
  0.09 
ndispl
    50  
 npart    temp    rho
   100     2.0  ${rho} 
 epsilon sigma  mass  cutoff
 1.0     1.0    1.0   5.0
endofdata

time  ../Source/mc_nvt.exe
mv fort.66 energy
mv fort.67 pressure
rm input
end
exit
