#! /bin/csh -f
#
# NPART    = NUMBER OF PARTICLES
# NSTEP    = NUMBER OF TIMESTEPS (x 1000)
# NINIT    = NUMBER OF INITIALIZATION STEPS
# DISPMAX = MAXIMUM DISPLACEMENT
# VOLMAX  = MAXIMUM VOLUME CHANGE
# BETA     = INVERSE TEMPERATURE
# PRESSURE = PRESURE

set NSTEP     = 1000
set NINIT     = 200
set NPART     = 100
set DISPMAX   = 1.0
set VOLMAX    = 0.01
set BETA      = 1.0

foreach PRESSURE (1.0) 
cat > input <<endofdata
$NSTEP $NINIT $NPART $DISPMAX $VOLMAX $BETA $PRESSURE
endofdata
time ../Source/mc-npt.exe
end
mv fort.22 movie.pdb
rm input 
exit
